/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package so.dang.cool.openfga.preview;

import com.fasterxml.jackson.databind.json.JsonMapper;
import dev.openfga.api.OpenFgaApi;
import dev.openfga.api.invoker.ApiClient;
import dev.openfga.api.invoker.ApiException;
import dev.openfga.api.model.CreateStoreRequest;

import java.net.http.HttpClient;

public class CreateStore {
    public static void main(String[] args) throws ApiException {
        // Setup
        var config = ApiClient.Configuration.of("http://localhost:8080");
        var apiClient = new ApiClient(HttpClient.newBuilder(), new JsonMapper().findAndRegisterModules(), config);
        var fga = new OpenFgaApi(apiClient);

        // Create a Store
        String storeName = "demo-store";
        var request = new CreateStoreRequest().name(storeName);

        var response = fga.createStore(request);

        // Show
        System.out.printf("The Store ID is: %s\n", response.getId());
    }
}
