/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package so.dang.cool.openfga.preview;

import com.fasterxml.jackson.databind.json.JsonMapper;
import dev.openfga.sdk.api.OpenFgaApi;
import dev.openfga.sdk.api.client.ApiClient;
import dev.openfga.sdk.api.configuration.Configuration;
import dev.openfga.sdk.api.model.CreateStoreRequest;

import java.net.http.HttpClient;

public class CreateStore {
    public static void main(String[] args) throws Exception {
        // Setup
        var config = new Configuration("http://localhost:8080");
        var apiClient = new ApiClient(HttpClient.newBuilder(), new JsonMapper().findAndRegisterModules());
        var fga = new OpenFgaApi(apiClient, config);

        // Create a Store
        String storeName = "demo-store";
        var request = new CreateStoreRequest().name(storeName);

        var response = fga.createStore(request).get();

        // Show
        System.out.printf("The Store ID is: %s\n", response.getId());
    }
}
