/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package so.dang.cool.openfga.preview;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
