/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package so.dang.cool.openfga.preview;

import static so.dang.cool.openfga.preview.GlobalConstants.*;

import dev.openfga.sdk.api.client.OpenFgaClient;
import dev.openfga.sdk.api.configuration.ClientConfiguration;
import dev.openfga.sdk.api.configuration.ClientCredentials;
import dev.openfga.sdk.api.configuration.Credentials;

public class ReadAuthModels {
    public static void main(String[] args) throws Exception {
        // Setup
        var config = new ClientConfiguration()
                .apiUrl(FGA_SERVER_URL)
                .storeId(FGA_STORE_ID)
                .credentials(new Credentials(new ClientCredentials()
                        .apiTokenIssuer(FGA_API_TOKEN_ISSUER)
                        .apiAudience(FGA_API_AUDIENCE)
                        .clientId(FGA_CLIENT_ID)
                        .clientSecret(FGA_CLIENT_SECRET)));
        var fga = new OpenFgaClient(config);

        // Read Auth Models
        var response = fga.readAuthorizationModels().get();

        // Show
        System.out.printf("The models are: %s\n", response.getAuthorizationModels());
    }
}
